import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //todo falta usar sass, react, migasde pan seo en react express servidor
  
  return (
    <html lang="en">
      <body>
        <header className="h-16 flex bg-yellow-300 ">
          <form action="/items" className="m-auto px-4 gap-4 flex flex-1 max-w-screen-xl">
            <input name="search" className="h-8 px-2 flex-1" type="text" />
            <button className="h-8 bg-gray-200 px-2 py-1 text-slate-700" type="submit">Buscar</button>
          </form>
        </header>
        <main className="max-x-screen-xl p-4">{children}</main>
      </body>
    </html>
  );
}
